alter table ECR_ALSDATACHECK modify LOANCONTRACTNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify LOANDUEBILLNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify FACTORINGNUM NUMBER(22,0);
--在终端运行db2 reorg table ECR_ALSDATACHECK
alter table ECR_ALSDATACHECK modify DISCOUNTNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify FINAINFONUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify FINADUEBILLNUM NUMBER(22,0);
--在终端运行db2 reorg table ECR_ALSDATACHECK
alter table ECR_ALSDATACHECK modify CREDITLETTERNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify GUARANTEEBILLNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify ACCEPTNUM NUMBER(22,0);
--在终端运行db2 reorg table ECR_ALSDATACHECK
alter table ECR_ALSDATACHECK modify CUSTOMERCREDITNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify ASSURECONTNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify GUARANTYCONTNUM NUMBER(22,0);
--在终端运行db2 reorg table ECR_ALSDATACHECK
alter table ECR_ALSDATACHECK modify IMPAWNCONTNUM NUMBER(22,0);
alter table ECR_ALSDATACHECK modify FLOORFUNDNUM NUMBER(22,0);

alter table BANK_ACCEPTANCE modify ASSURESCALE NUMBER(3,0);

alter table BANK_ASSURECONT add CERTTYPE VARCHAR2(20);
alter table BANK_ASSURECONT add CERTID VARCHAR2(20);
alter table BANK_ASSURECONT add REPORTTYPE VARCHAR2(20);

alter table BANK_GUARANTYCONT modify GUARANTYNO VARCHAR2(2);
alter table BANK_GUARANTYCONT add CERTTYPE VARCHAR2(20);
alter table BANK_GUARANTYCONT add CERTID VARCHAR2(20);
alter table BANK_GUARANTYCONT add REPORTTYPE VARCHAR2(20);

alter table BANK_IMPAWNCONT modify IMPAWNO VARCHAR2(2);
alter table BANK_IMPAWNCONT add CERTTYPE VARCHAR2(20);
alter table BANK_IMPAWNCONT add CERTID VARCHAR2(20);
alter table BANK_IMPAWNCONT add REPORTTYPE VARCHAR2(20);



  
    
