reorg table ECR_ERRMAP@
reorg table ECR_ACCEPTANCE@
reorg table ECR_ASSURECONT@
reorg table ECR_CREDITLETTER@
reorg table ECR_CUSTOMERCREDIT@
reorg table ECR_ERRHISTORY@
reorg table ECR_ERRRECORD@
reorg table ECR_FEEDBACK@
reorg table ECR_FINARETURN@
reorg table ECR_FLOORFUND@
reorg table ECR_GUARANTEEBILL@
reorg table ECR_GUARANTYCONT@
reorg table ECR_IMPAWNCONT@
reorg table ECR_LOANCONTRACT@
reorg table ECR_LOANDUEBILL@
reorg table ECR_LOANEXTENSION@
reorg table ECR_LOANRETURN@
reorg table ECR_REPORTSTATUS@
reorg table ECR_SESSION@
reorg table ECR_ALSDATACHECK@
reorg table BANK_ACCEPTANCE@
reorg table BANK_ASSURECONT@
reorg table BANK_GUARANTYCONT@
reorg table BANK_IMPAWNCONT@
reorg table HIS_ACCEPTANCE@
reorg table HIS_ASSURECONT@
reorg table HIS_CREDITLETTER@
reorg table HIS_CUSTOMERCREDIT@
reorg table HIS_FINARETURN@
reorg table HIS_FLOORFUND@
reorg table HIS_GUARANTEEBILL@
reorg table HIS_GUARANTYCONT@
reorg table HIS_IMPAWNCONT@
reorg table HIS_LOANCONTRACT@
reorg table HIS_LOANDUEBILL@
reorg table HIS_LOANEXTENSION@
reorg table HIS_LOANRETURN@
